import os
import subprocess

files_to_move = {
    # docflow
    "baixar_processos_referenciados_pw.js": "docflow",
    "discover_docflow_sso.js": "docflow",
    "docflow_baixar_projetos_anapolis.js": "docflow",
    "docflow_baixar_projetos_goiania.js": "docflow",
    "docflow_consulta_massa_2026.js": "docflow",
    "docflow_consulta_massa_anos.js": "docflow",
    "docflow_consultar_processo.js": "docflow",
    "docflow_direct_http.js": "docflow",
    "docflow_direct_http_downloader.js": "docflow",
    "docflow_download_anexos.js": "docflow",
    "docflow_dynamic_http.js": "docflow",
    "docflow_playwright_then_http.js": "docflow",
    "docflow_zk_direct.js": "docflow",
    "explore_docflow_menus.js": "docflow",
    "extract_docflow.js": "docflow",
    "inspect_docflow_login.js": "docflow",
    "inspect_dtid.js": "docflow",
    "inspect_dtid_2.js": "docflow",
    "integrar_projetos_locais_anapolis.js": "docflow",
    "map_consulta_protocolo_http.js": "docflow",
    "map_docflow_processo.js": "docflow",
    "organizar_anexos_anapolis.js": "docflow",
    "organizar_anexos_goiania.js": "docflow",
    "reconstruir_base_estrita.py": "docflow",
    "test_anonimo_3648437.js": "docflow",
    "test_busca_protocolo_3648437.js": "docflow",
    "test_busca_qualquer_estado.js": "docflow",
    "test_coleta_metadados_3648437.js": "docflow",
    "test_consulta_sem_historico.js": "docflow",
    "test_docflow.js": "docflow",
    "test_docflow_download_http.js": "docflow",
    "test_docflow_expedido.js": "docflow",
    "test_docflow_jsf_fix.js": "docflow",
    "test_docflow_protocolo_http_benchmark.js": "docflow",
    "test_docflow_pure_http.js": "docflow",
    "test_docflow_session.js": "docflow",
    "test_docflow_sign_checker.js": "docflow",
    "test_docflow_urls.js": "docflow",
    "test_executar_busca_protocolo.js": "docflow",
    "test_pesquisa_avancada.js": "docflow",
    "test_protocolo_playwright.js": "docflow",
    "test_richfaces_ajax.js": "docflow",
    "test_search_processo_http.js": "docflow",
    "test_varrer_metadados.js": "docflow",
    "verificar_processos_referenciados.js": "docflow",
    "watcher_organizar_anapolis.js": "docflow",
    "run_all_years.js": "docflow",
    "test_all_docflow_combinations.js": "docflow",
    "dashboard_projetos.html": "docflow",
    "get_folders.js": "zimbra",
    "check_inbox_ui.js": "zimbra",
    "check_unread.js": "zimbra",
    "check_webmail.js": "zimbra",
    "check_webmail2.js": "zimbra",
    "classify_emails.js": "zimbra",
    "consultar_contas_especificas.js": "zimbra",
    "debug_zimbra.js": "zimbra",
    "extract_caixa_conteudo.js": "zimbra",
    "extract_full_caixa.js": "zimbra",
    "extract_item_details.js": "zimbra",
    "get_headers.js": "zimbra",
    "move_conversations.js": "zimbra",
    "organize_zimbra.js": "zimbra",
    "print_posts.js": "zimbra",
    "print_responses.js": "zimbra",
    "reorganize_folders.js": "zimbra",
    "scratch_caixa_conteudo.json": "zimbra",
    "scratch_evaluated_emails.json": "zimbra",
    "scratch_folders_json.json": "zimbra",
    "scratch_folders_soap.xml": "zimbra",
    "scratch_full_caixa.json": "zimbra",
    "scratch_tags_json.json": "zimbra",
    "scratch_tags_soap.xml": "zimbra",
    "scratch_zimbra_body.txt": "zimbra",
    "scratch_zimbra_rest.json": "zimbra",
    "sniff_zimbra.js": "zimbra",
    "test_conv_move.js": "zimbra",
    "test_soap_auth.js": "zimbra",
    "test_soap_csrf.js": "zimbra",
    "test_untag.js": "zimbra",
    "test_zimbra_fetch.js": "zimbra",
    "test_zimbra_json_soap.js": "zimbra",
    "test_zimbra_rest.js": "zimbra",
    "zimbra_meta.js": "zimbra",
    "test_deep_map_supervisorio.js": "supervisorio",
    "test_inspect_supervisorio.js": "supervisorio",
    "test_live_supervisorio.js": "supervisorio",
    "test_map_all_supervisorio.js": "supervisorio",
    "test_open_supervisorio.js": "supervisorio",
    "test_pure_http_supervisorio.js": "supervisorio",
    "scratch_goialandia_7dias.json": "supervisorio",
    "scratch_goialandia_leituras.json": "supervisorio",
    "scratch_rap_goialandia.json": "supervisorio",
    "scratch_historico.js": "supervisorio",
    "scratch_historico_page.html": "supervisorio",
    "grafico_rap_bomba_goialandia_48h.html": "supervisorio",
    "grafico_rap_bomba_goialandia_7dias.html": "supervisorio",
    "grafico_rap_goialandia.html": "supervisorio",
    "analyze_eco187_log.js": "eco",
    "check_ra_eco701.js": "eco",
    "debug_eco187_http.js": "eco",
    "executar_varredura_eco187.js": "eco",
    "inspect_eco709_state.js": "eco",
    "query_eco707_rua.js": "eco",
    "query_eco711.js": "eco",
    "query_eco711_complete.js": "eco",
    "test_eco187_capture_http.js": "eco",
    "test_eco187_direct_http.js": "eco",
    "test_eco187_playwright_http.js": "eco",
    "test_eco187_search.js": "eco",
    "test_eco709.js": "eco",
    "test_eco709_detailed.js": "eco",
    "test_eco709_fill.js": "eco",
    "test_eco711.js": "eco",
    "test_eco711_situacao.js": "eco",
    "test_bairro_popup.js": "eco",
    "test_bairro_select.js": "eco",
    "test_bairro_select2.js": "eco",
    "test_logradouro_select.js": "eco",
    "query_agosto_itororo.js": "eco",
    "query_all_itororo.js": "eco",
    "query_itororo_ras.js": "eco",
    "query_ras_completo.js": "eco",
    "query_rua_asfalto.js": "eco",
    "query_rua_correa_camargo.js": "eco",
    "serve_monitor_varredura.js": "eco",
    "test_abrir_ra.js": "eco",
    "test_apps_ra.js": "eco",
    "capture_network_traffic.js": "misc",
    "extract_panels.js": "misc",
    "test_action.js": "misc",
    "test_batch_exec.js": "misc",
    "test_check_dmc.js": "misc",
    "test_check_frames.js": "misc",
    "test_debug_login.js": "misc",
    "test_direct_flow.js": "misc",
    "test_direct_http_full.js": "misc",
    "test_direct_urls.js": "misc",
    "test_dump_dashboard.js": "misc",
    "test_extract_endpoints_from_js.js": "misc",
    "test_inspect_endpoints.js": "misc",
    "test_inspect_frames.js": "misc",
    "test_inspect_js.js": "misc",
    "test_inspect_menu.js": "misc",
    "test_inspect_more_apis.js": "misc",
    "test_nav_ok.js": "misc",
    "test_sniff_http_flow.js": "misc",
    "test_systems_menu.js": "misc",
    "test_updated_pass.js": "misc",
    "test_ad_username_variants.js": "misc",
    "test_apps.js": "misc",
    "test_sniff_autenticar.js": "misc",
    "agy_run.log": "misc"
}

with open("scratch/exploracao/INVENTARIO.md", "w") as f:
    f.write("# Inventário de Movimentação - Fase 11\n\n")
    f.write("| Arquivo Original | Novo Caminho | Vertical |\n")
    f.write("|---|---|---|\n")

    for file, vertical in files_to_move.items():
        if os.path.isfile(file):
            dest = f"scratch/exploracao/{vertical}/{file}"
            
            # Check if tracked by git
            tracked = subprocess.run(["git", "ls-files", "--error-unmatch", file], capture_output=True).returncode == 0
            
            if tracked:
                subprocess.run(["git", "mv", file, dest], check=True)
            else:
                os.rename(file, dest)
                
            f.write(f"| {file} | {dest} | {vertical} |\n")

print("Done")
