#!/usr/bin/env bash
set -e

declare -A files_to_move

# docflow
files_to_move[baixar_processos_referenciados_pw.js]="docflow"
files_to_move[discover_docflow_sso.js]="docflow"
files_to_move[docflow_baixar_projetos_anapolis.js]="docflow"
files_to_move[docflow_baixar_projetos_goiania.js]="docflow"
files_to_move[docflow_consulta_massa_2026.js]="docflow"
files_to_move[docflow_consulta_massa_anos.js]="docflow"
files_to_move[docflow_consultar_processo.js]="docflow"
files_to_move[docflow_direct_http.js]="docflow"
files_to_move[docflow_direct_http_downloader.js]="docflow"
files_to_move[docflow_download_anexos.js]="docflow"
files_to_move[docflow_dynamic_http.js]="docflow"
files_to_move[docflow_playwright_then_http.js]="docflow"
files_to_move[docflow_zk_direct.js]="docflow"
files_to_move[explore_docflow_menus.js]="docflow"
files_to_move[extract_docflow.js]="docflow"
files_to_move[inspect_docflow_login.js]="docflow"
files_to_move[inspect_dtid.js]="docflow"
files_to_move[inspect_dtid_2.js]="docflow"
files_to_move[integrar_projetos_locais_anapolis.js]="docflow"
files_to_move[map_consulta_protocolo_http.js]="docflow"
files_to_move[map_docflow_processo.js]="docflow"
files_to_move[organizar_anexos_anapolis.js]="docflow"
files_to_move[organizar_anexos_goiania.js]="docflow"
files_to_move[reconstruir_base_estrita.py]="docflow"
files_to_move[test_anonimo_3648437.js]="docflow"
files_to_move[test_busca_protocolo_3648437.js]="docflow"
files_to_move[test_busca_qualquer_estado.js]="docflow"
files_to_move[test_coleta_metadados_3648437.js]="docflow"
files_to_move[test_consulta_sem_historico.js]="docflow"
files_to_move[test_docflow.js]="docflow"
files_to_move[test_docflow_download_http.js]="docflow"
files_to_move[test_docflow_expedido.js]="docflow"
files_to_move[test_docflow_jsf_fix.js]="docflow"
files_to_move[test_docflow_protocolo_http_benchmark.js]="docflow"
files_to_move[test_docflow_pure_http.js]="docflow"
files_to_move[test_docflow_session.js]="docflow"
files_to_move[test_docflow_sign_checker.js]="docflow"
files_to_move[test_docflow_urls.js]="docflow"
files_to_move[test_executar_busca_protocolo.js]="docflow"
files_to_move[test_pesquisa_avancada.js]="docflow"
files_to_move[test_protocolo_playwright.js]="docflow"
files_to_move[test_richfaces_ajax.js]="docflow"
files_to_move[test_search_processo_http.js]="docflow"
files_to_move[test_varrer_metadados.js]="docflow"
files_to_move[verificar_processos_referenciados.js]="docflow"
files_to_move[watcher_organizar_anapolis.js]="docflow"
files_to_move[run_all_years.js]="docflow"
files_to_move[test_all_docflow_combinations.js]="docflow"
files_to_move[dashboard_projetos.html]="docflow"

# zimbra
files_to_move[check_inbox_ui.js]="zimbra"
files_to_move[check_unread.js]="zimbra"
files_to_move[check_webmail.js]="zimbra"
files_to_move[check_webmail2.js]="zimbra"
files_to_move[classify_emails.js]="zimbra"
files_to_move[consultar_contas_especificas.js]="zimbra"
files_to_move[debug_zimbra.js]="zimbra"
files_to_move[extract_caixa_conteudo.js]="zimbra"
files_to_move[extract_full_caixa.js]="zimbra"
files_to_move[extract_item_details.js]="zimbra"
files_to_move[get_folders.js]="zimbra"
files_to_move[get_headers.js]="zimbra"
files_to_move[move_conversations.js]="zimbra"
files_to_move[organize_zimbra.js]="zimbra"
files_to_move[print_posts.js]="zimbra"
files_to_move[print_responses.js]="zimbra"
files_to_move[reorganize_folders.js]="zimbra"
files_to_move[scratch_caixa_conteudo.json]="zimbra"
files_to_move[scratch_evaluated_emails.json]="zimbra"
files_to_move[scratch_folders_json.json]="zimbra"
files_to_move[scratch_folders_soap.xml]="zimbra"
files_to_move[scratch_full_caixa.json]="zimbra"
files_to_move[scratch_tags_json.json]="zimbra"
files_to_move[scratch_tags_soap.xml]="zimbra"
files_to_move[scratch_zimbra_body.txt]="zimbra"
files_to_move[scratch_zimbra_rest.json]="zimbra"
files_to_move[sniff_zimbra.js]="zimbra"
files_to_move[test_conv_move.js]="zimbra"
files_to_move[test_soap_auth.js]="zimbra"
files_to_move[test_soap_csrf.js]="zimbra"
files_to_move[test_untag.js]="zimbra"
files_to_move[test_zimbra_fetch.js]="zimbra"
files_to_move[test_zimbra_json_soap.js]="zimbra"
files_to_move[test_zimbra_rest.js]="zimbra"
files_to_move[zimbra_meta.js]="zimbra"

# supervisorio
files_to_move[test_deep_map_supervisorio.js]="supervisorio"
files_to_move[test_inspect_supervisorio.js]="supervisorio"
files_to_move[test_live_supervisorio.js]="supervisorio"
files_to_move[test_map_all_supervisorio.js]="supervisorio"
files_to_move[test_open_supervisorio.js]="supervisorio"
files_to_move[test_pure_http_supervisorio.js]="supervisorio"
files_to_move[scratch_goialandia_7dias.json]="supervisorio"
files_to_move[scratch_goialandia_leituras.json]="supervisorio"
files_to_move[scratch_rap_goialandia.json]="supervisorio"
files_to_move[scratch_historico.js]="supervisorio"
files_to_move[scratch_historico_page.html]="supervisorio"
files_to_move[grafico_rap_bomba_goialandia_48h.html]="supervisorio"
files_to_move[grafico_rap_bomba_goialandia_7dias.html]="supervisorio"
files_to_move[grafico_rap_goialandia.html]="supervisorio"

# eco
files_to_move[analyze_eco187_log.js]="eco"
files_to_move[check_ra_eco701.js]="eco"
files_to_move[debug_eco187_http.js]="eco"
files_to_move[executar_varredura_eco187.js]="eco"
files_to_move[inspect_eco709_state.js]="eco"
files_to_move[query_eco707_rua.js]="eco"
files_to_move[query_eco711.js]="eco"
files_to_move[query_eco711_complete.js]="eco"
files_to_move[test_eco187_capture_http.js]="eco"
files_to_move[test_eco187_direct_http.js]="eco"
files_to_move[test_eco187_playwright_http.js]="eco"
files_to_move[test_eco187_search.js]="eco"
files_to_move[test_eco709.js]="eco"
files_to_move[test_eco709_detailed.js]="eco"
files_to_move[test_eco709_fill.js]="eco"
files_to_move[test_eco711.js]="eco"
files_to_move[test_eco711_situacao.js]="eco"
files_to_move[test_bairro_popup.js]="eco"
files_to_move[test_bairro_select.js]="eco"
files_to_move[test_bairro_select2.js]="eco"
files_to_move[test_logradouro_select.js]="eco"
files_to_move[query_agosto_itororo.js]="eco"
files_to_move[query_all_itororo.js]="eco"
files_to_move[query_itororo_ras.js]="eco"
files_to_move[query_ras_completo.js]="eco"
files_to_move[query_rua_asfalto.js]="eco"
files_to_move[query_rua_correa_camargo.js]="eco"
files_to_move[serve_monitor_varredura.js]="eco"
files_to_move[test_abrir_ra.js]="eco"
files_to_move[test_apps_ra.js]="eco"

# misc
files_to_move[capture_network_traffic.js]="misc"
files_to_move[extract_panels.js]="misc"
files_to_move[test_action.js]="misc"
files_to_move[test_batch_exec.js]="misc"
files_to_move[test_check_dmc.js]="misc"
files_to_move[test_check_frames.js]="misc"
files_to_move[test_debug_login.js]="misc"
files_to_move[test_direct_flow.js]="misc"
files_to_move[test_direct_http_full.js]="misc"
files_to_move[test_direct_urls.js]="misc"
files_to_move[test_dump_dashboard.js]="misc"
files_to_move[test_extract_endpoints_from_js.js]="misc"
files_to_move[test_inspect_endpoints.js]="misc"
files_to_move[test_inspect_frames.js]="misc"
files_to_move[test_inspect_js.js]="misc"
files_to_move[test_inspect_menu.js]="misc"
files_to_move[test_inspect_more_apis.js]="misc"
files_to_move[test_nav_ok.js]="misc"
files_to_move[test_sniff_http_flow.js]="misc"
files_to_move[test_systems_menu.js]="misc"
files_to_move[test_updated_pass.js]="misc"
files_to_move[test_ad_username_variants.js]="misc"
files_to_move[test_apps.js]="misc"
files_to_move[test_sniff_autenticar.js]="misc"
files_to_move[agy_run.log]="misc"

INVENTORY_FILE="scratch/exploracao/INVENTARIO.md"

echo "# Inventário de Movimentação - Fase 11" > "$INVENTORY_FILE"
echo "" >> "$INVENTORY_FILE"
echo "| Arquivo Original | Novo Caminho | Vertical |" >> "$INVENTORY_FILE"
echo "|---|---|---|" >> "$INVENTORY_FILE"

for file in "${!files_to_move[@]}"; do
    if [ -f "$file" ]; then
        vertical="${files_to_move[$file]}"
        dest="scratch/exploracao/$vertical/$file"
        
        # Check if tracked by git
        if git ls-files --error-unmatch "$file" >/dev/null 2>&1; then
            git mv "$file" "$dest"
        else
            mv "$file" "$dest"
        fi
        
        echo "| $file | $dest | $vertical |" >> "$INVENTORY_FILE"
    fi
done

echo "Done moving files and generated inventory."
